Repository yulpumta-clone-team/Co-nect, pull requests merged in 2022-04, with the labels that each got.

#7 Issue tester#6
  webapp/README.md
Labels: Document, FE, Chore

#11 issue, pr test #9
  README.md
Labels: BE, Chore

#16 Develop -> Front 브랜치 최신화
  .gitignore
  src/main/generated/com/projectmatching/app/domain/comment/entity/QTeamComment.java
  src/main/generated/com/projectmatching/app/domain/team/entity/QTeam.java
  src/main/generated/com/projectmatching/app/domain/user/entity/QUser.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserProfileDto.java
Labels: FE, Update

#18 댓글 API 수정 #15
  .gitignore
  src/main/generated/com/projectmatching/app/domain/comment/entity/QTeamComment.java
  src/main/generated/com/projectmatching/app/domain/team/entity/QTeam.java
  src/main/generated/com/projectmatching/app/domain/user/entity/QUser.java
  src/main/java/com/projectmatching/app/controller/comment/TeamCommentController.java
  src/main/java/com/projectmatching/app/domain/comment/repository/TeamCommentRepository.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamDetailResponseDto.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamResponseDto.java
  src/main/java/com/projectmatching/app/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserProfileDto.java
  src/main/java/com/projectmatching/app/service/comment/CommentService.java
  src/main/java/com/projectmatching/app/service/comment/CommentServiceImpl.java
  src/main/java/com/projectmatching/app/service/team/TeamService.java
Labels: Refactor, BE

#20 Test : jwtService 테스트 코드 작성
  src/main/java/com/projectmatching/app/util/AuthTokenProvider.java
  src/test/java/com/projectmatching/app/service/ServiceTest.java
  src/test/java/com/projectmatching/app/service/jwt/JwtServiceTest.java
Labels: BE, Test

#19 Feat: Sign up 페이지 제작 #14
  webapp/src/pages/NewPost/index.jsx
  webapp/src/pages/SignUp/index.jsx
Labels: Refactor, FE

#24 Refactor: signup #14
  webapp/src/apiAction/auth.js
  webapp/src/components/MdEditor/index.jsx
  webapp/src/components/Navigation/LoginNav.jsx
  webapp/src/components/Navigation/index.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/utils/cookie.js
Labels: Refactor, FE

#31 팀생성페이지 제출 양식 수정
  webapp/src/_actions/team_action.js
  webapp/src/_reducers/team_reducer.js
  webapp/src/_types/teamTypes.js
  webapp/src/api/team.js
  webapp/src/apiAction/team.js
  webapp/src/constant/index.js
  webapp/src/layouts/App/index.js
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/NewPost/index.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/NewTeamPost/style.js
  webapp/src/pages/SignUp/index.jsx
Labels: Feat, FE
