Repository yulpumta-clone-team/Co-nect, pull requests merged in 2022-09, with the labels that each got.

#167 [FE] NewTeamPost - css
  webapp/src/App.jsx
  webapp/src/assets/icons/add-img.svg
  webapp/src/assets/icons/edit.svg
  webapp/src/pages/NewTeamPost/NewTeamPost.style.js
  webapp/src/pages/NewTeamPost/NewTeamPost.view.jsx
  webapp/src/pages/NewTeamPost/NewTeamPostDetail.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/NewTeamPost/style.js
  webapp/src/service/team.parser.js
  webapp/src/service/team.validation.js
  webapp/src/types/team.type.js
Labels: FE, Design

#168 [FE] 유저 프로필 수정 페이지 기능 수정 (마크다운에디터, 기술스택, 버튼활성화로직)
  webapp/src/api/user.api.js
  webapp/src/components/MarkdownEditor/index.jsx
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hooks/useCheckNicknameDuplicate.js
  webapp/src/hooks/useFileUploader.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/pages/EditUserProfile/EditUserProfile.view.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileDetail.jsx
  webapp/src/service/skillStack.parser.js
  webapp/src/service/user.parser.js
Labels: Fix, FE

#170 [FE] 팀 카드 css 수정
  webapp/src/components/TeamCard/TeamCard.stories.jsx
  webapp/src/components/TeamCard/TeamCard.style.js
  webapp/src/components/TeamCard/index.jsx
  webapp/src/mocks/teamHandler.mock/teamsList.js
  webapp/src/service/team.parser.js
Labels: Fix, FE

#173 [FE] TeamPostDetail - css
  webapp/src/assets/icons/blue-heart.svg
  webapp/src/mocks/teamHandler.mock/teamDetail.js
  webapp/src/pages/TeamPost/TeamPost.style.js
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/TeamPost/index.jsx
  webapp/src/pages/TeamPost/style.js
  webapp/src/service/team.parser.js
  webapp/src/types/team.type.js
Labels: FE, Design

#174 [FE] 기술스택 css 수정 + api로 받아오기
  webapp/.storybook/preview.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Common/Divider/index.jsx
  webapp/src/components/GlobalNavigation/LoginNavigation.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackOptions.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.style.js
  webapp/src/components/TechStackSelectInput/TechStackSelectedViewer.jsx
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/mocks/etcHandler.mock/index.js
  webapp/src/mocks/mockUtils.js
  webapp/src/pages/EditUserProfile/EditUserProfile.style.js
  webapp/src/pages/EditUserProfile/EditUserProfile.view.jsx
  webapp/src/pages/EssentialInfo/EssentialInfo.stories.jsx
  webapp/src/pages/EssentialInfo/EssentialInfo.style.js
  webapp/src/pages/EssentialInfo/SubPages/Skills.jsx
  webapp/src/pages/EssentialInfo/index.jsx
  webapp/src/pages/Login/Login.stories.jsx
  webapp/src/pages/NewTeamPost/NewTeamPostDetail.jsx
  webapp/src/pages/SignUp/SignUp.stories.jsx
  webapp/src/service/skillStack.parser.js
Labels: Feat, FE, Design

#175 Refact/team 팀 서비스 로직 수정 및 리팩토링
  build.gradle
  gradlew
  lombok.config
  src/main/generated/com/projectmatching/app/domain/team/entity/QTeam.java
  src/main/java/com/projectmatching/app/annotation/Generated.java
  src/main/java/com/projectmatching/app/constant/FilterPatternConstant.java
  src/main/java/com/projectmatching/app/controller/history/TeamHistoryController.java
  src/main/java/com/projectmatching/app/controller/team/TeamController.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamDetailResponseDto.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamDto.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamRequestDto.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamResponseDto.java
  src/main/java/com/projectmatching/app/domain/team/dto/TeamSimpleDto.java
  src/main/java/com/projectmatching/app/domain/team/entity/Team.java
  src/main/java/com/projectmatching/app/domain/team/entity/TeamTech.java
  src/main/java/com/projectmatching/app/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/projectmatching/app/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/projectmatching/app/domain/team/repository/TeamTechRepository.java
  src/main/java/com/projectmatching/app/domain/techStack/entity/TechStack.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserDto.java
  src/main/java/com/projectmatching/app/domain/user/entity/User.java
  src/main/java/com/projectmatching/app/domain/user/entity/UserTeam.java
  src/main/java/com/projectmatching/app/exception/CoNectLogicalException.java
  src/main/java/com/projectmatching/app/exception/CoNectNotFoundException.java
  src/main/java/com/projectmatching/app/service/history/Impl/TeamHistoryServiceImpl.java
  src/main/java/com/projectmatching/app/service/history/TeamHistoryService.java
  src/main/java/com/projectmatching/app/service/team/TeamService.java
  src/main/java/com/projectmatching/app/service/user/userdetail/UserDetailsImpl.java
  src/test/java/com/projectmatching/app/DemoApplicationTests.java
  src/test/java/com/projectmatching/app/controller/user/UserControllerTest.java
  src/test/java/com/projectmatching/app/service/ServiceTest.java
  src/test/java/com/projectmatching/app/service/team/TeamDeleteTest.java
  src/test/java/com/projectmatching/app/service/team/TeamReadTest.java
  src/test/java/com/projectmatching/app/service/team/TeamSaveTest.java
  src/test/java/com/projectmatching/app/service/team/TeamServiceTest.java
  src/test/java/com/projectmatching/app/service/team/TeamUpdateTest.java
Labels: BE

#178 [FE] 팀 생성 API 연결 수정
  webapp/src/components/TechStackSelectInput/TechStackOptions.jsx
  webapp/src/pages/NewTeamPost/NewTeamPost.view.jsx
  webapp/src/pages/NewTeamPost/NewTeamPostDetail.jsx
  webapp/src/service/team.parser.js
  webapp/src/service/team.validation.js
  webapp/src/types/user.type.js
Labels: Fix, FE

#183 [FE] utils, service, hooks 폴더 정리 (jsdoc 활용)
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.jsx
  webapp/src/components/MarkdownEditor/index.jsx
  webapp/src/components/TeamCard/index.jsx
  webapp/src/components/TechSkills/index.jsx
  webapp/src/components/TechStackSelectInput/TechStackOptions.jsx
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/components/UserCard/index.jsx
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hooks/useAxios.js
  webapp/src/hooks/useCheckNicknameDuplicate.js
  webapp/src/hooks/useDropdown.js
  webapp/src/hooks/useFileUploader.js
  webapp/src/hooks/useForm.js
  webapp/src/hooks/useIntersect.js
  webapp/src/hooks/useSkillCarousel.js
  webapp/src/hooks/useUserInfo.js
  webapp/src/mocks/userHandler.mock/essentialInfo.js
  webapp/src/mocks/userHandler.mock/userDetail.js
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileDetail.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/NewTeamPost/NewTeamPostDetail.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/service/auth/auth.parser.js
  webapp/src/service/auth/auth.validation.js
  webapp/src/service/auth/index.js
  webapp/src/service/essentialForm.validation.js
  webapp/src/service/etc/skillStack.parser.js
  webapp/src/service/login.validation.js
  webapp/src/service/signUp.validation.js
  webapp/src/service/team.parser.js
  webapp/src/service/team.validation.js
  webapp/src/service/team/team.parser.js
  webapp/src/service/team/team.validation.js
  webapp/src/service/user.parser.js
  webapp/src/service/user.validation.js
  webapp/src/service/user/user.parser.js
  webapp/src/service/user/user.validation.js
  webapp/src/types/team.type.js
  webapp/src/types/team.typedef.js
  webapp/src/types/techSkill.typedef.js
  webapp/src/types/user.type.js
  webapp/src/types/user.typedef.js
  webapp/src/utils/customProptypes.js
  webapp/src/utils/index.js
Labels: Document, FE

#181 [FE] MyList - css
  webapp/src/components/Common/Tabs/style.js
  webapp/src/layouts/style.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/pages/MyList/MyList.stories.jsx
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/MyList/style.js
  webapp/src/pages/TeamBoard/style.js
  webapp/src/pages/UserBoard/style.js
Labels: FE, Design

#184 [FE] MyPost - css
  webapp/src/pages/MyPost/index.jsx
  webapp/src/pages/MyPost/style.js
Labels: FE, Design

#193 [FE] 댓글 컴포넌트 css작업
  webapp/src/assets/icons/chat.svg
  webapp/src/assets/icons/check-rectangle.svg
  webapp/src/assets/icons/heart-full.svg
  webapp/src/assets/icons/heart.svg
  webapp/src/assets/icons/lock.svg
  webapp/src/assets/icons/polygon-down.svg
  webapp/src/assets/icons/polygon-up.svg
  webapp/src/assets/icons/rectangle.svg
  webapp/src/assets/icons/recycle-bin.svg
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.stories.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.stories.jsx
  webapp/src/components/ComentContainer/CommentElement/Secret.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.CommentForm.stories.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Reply.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Root.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Edit.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.stories.jsx
  webapp/src/components/ComentContainer/CommentList/Root.CommentList.jsx
  webapp/src/components/ComentContainer/Hoc/Hoc.NestedComment.jsx
  webapp/src/components/ComentContainer/Hoc/HocSecretComment.jsx
  webapp/src/components/ComentContainer/LoadingCommentList.jsx
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/components/ComentContainer/style.js
  webapp/src/components/Common/CheckInput/CheckInput.stories.jsx
  webapp/src/components/Common/CheckInput/CheckInput.style.js
  webapp/src/components/Common/CheckInput/index.jsx
  webapp/src/components/Common/Form/index.jsx
  webapp/src/components/Common/TextArea/TextArea.style.js
  webapp/src/components/Common/TextArea/index.jsx
  webapp/src/contexts/Comment/useComments.js
  webapp/src/hooks/useForm.js
  webapp/src/mocks/commentHandler.mock/index.js
  webapp/src/pages/UserPost/UserPost.style.js
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/service/etc/comment.validation.js
  webapp/src/styles/theme.js
Labels: FE, Design

#187 [FE] 팀 게시글 수정 페이지 css 및 api 연결
  webapp/src/App.jsx
  webapp/src/api/user.api.js
  webapp/src/components/TeamCard/TeamCard.stories.jsx
  webapp/src/components/TeamCard/TeamCard.style.js
  webapp/src/components/TeamCard/index.jsx
  webapp/src/components/UserCard/UserCard.style.js
  webapp/src/constant/api.constant.js
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/mocks/teamHandler.mock/teamDetail.js
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditTeamPost/EditTeamPost.stories.jsx
  webapp/src/pages/EditTeamPost/EditTeamPost.style.js
  webapp/src/pages/EditTeamPost/EditTeamPost.view.jsx
  webapp/src/pages/EditTeamPost/EditTeamPostDetail.jsx
  webapp/src/pages/EditTeamPost/index.jsx
  webapp/src/pages/EditTeamPost/style.js
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/TeamPost/index.jsx
  webapp/src/service/team/team.parser.js
  webapp/src/service/team/team.validation.js
  webapp/src/types/team.type.js
  webapp/src/types/team.typedef.js
Labels: Feat, FE

#197 [FE] 팀 소속 여부 체크박스 컴포넌트 구현
  webapp/src/assets/icons/check-normal.svg
  webapp/src/components/TeamBelongCheckInput/TeamBelongCheckInput.stories.jsx
  webapp/src/components/TeamBelongCheckInput/TeamBelongCheckInput.style.js
  webapp/src/components/TeamBelongCheckInput/index.jsx
  webapp/src/constant/index.js
  webapp/src/pages/EditUserProfile/EditUserProfile.style.js
  webapp/src/pages/EditUserProfile/EditUserProfile.view.jsx
Labels: FE, Design

#190 [FE] TeamPost like + Like Component 구현
  webapp/src/api/team.api.js
  webapp/src/assets/icons/full-heart.svg
  webapp/src/assets/icons/red-heart.svg
  webapp/src/components/Common/Like/Like.jsx
  webapp/src/components/Common/Like/Like.stories.jsx
  webapp/src/components/Common/Like/LikeApi.jsx
  webapp/src/components/Common/Like/style.js
  webapp/src/components/TeamCard/index.jsx
  webapp/src/constant/api.constant.js
  webapp/src/contexts/Comment/useComments.js
  webapp/src/mocks/teamHandler.mock/index.js
  webapp/src/mocks/teamHandler.mock/teamsList.js
  webapp/src/pages/TeamPost/TeamPost.style.js
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
Labels: FE, Design

#199 [FE] 기술스택 팝업에서 선택한 목록 표시할 수 있는 옵션 추가
  webapp/src/components/TechStackSelectInput/TechStackOptions.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.style.js
  webapp/src/components/TechStackSelectInput/TechStackSelectedViewer.jsx
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/pages/EssentialInfo/SubPages/Skills.jsx
  webapp/src/pages/NewTeamPost/NewTeamPostDetail.jsx
Labels: Fix, FE, Design
