Repository yulpumta-clone-team/Co-nect, pull requests merged in 2022-08, with the labels that each got.

#111 [FE] proptypes 중앙관리
  webapp/src/api/team.js
  webapp/src/api/user.js
  webapp/src/components/ComentContainer/Comment.jsx
  webapp/src/components/Navigation/LoginNav.jsx
  webapp/src/components/TeamCard/index.jsx
  webapp/src/components/UserCard/index.jsx
  webapp/src/components/UserCard/style.js
  webapp/src/constant/api.js
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hoc/WithLoading.jsx
  webapp/src/hooks/useIntersect.js
  webapp/src/mocks/team/index.js
  webapp/src/mocks/user/index.js
  webapp/src/mocks/user/usersList.js
  webapp/src/pages/EditUserProfile/EdiitUserProfileForm.jsx
  webapp/src/pages/EditUserProfile/index.jsx
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/UserBoard/index.jsx
  webapp/src/types/comment.type.js
  webapp/src/types/team.type.js
  webapp/src/types/user.type.js
Labels: Document, FE

#117 [FE] 댓글 컴포넌트 리팩토링
  webapp/src/components/ComentContainer/Comment.jsx
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Reply.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Root.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Edit.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentList.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.jsx
  webapp/src/components/ComentContainer/CommentList/Root.CommentList.jsx
  webapp/src/components/ComentContainer/Hoc/Hoc.LoadingCommentList.jsx
  webapp/src/components/ComentContainer/Hoc/Hoc.NestedComment.jsx
  webapp/src/components/ComentContainer/Hoc/HocSecretComment.jsx
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/components/ComentContainer/style.js
  webapp/src/contexts/Comment/Comment.Provider.jsx
  webapp/src/contexts/Comment/useCommentApi.js
  webapp/src/contexts/Comment/useComments.js
  webapp/src/hoc/WithLoading.jsx
  webapp/src/hoc/withProvider.jsx
  webapp/src/hooks/useAxios.js
  webapp/src/mocks/comment/index.js
  webapp/src/mocks/comment/userComments.js
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditUserProfile/EdiitUserProfileForm.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/types/comment.type.js
  webapp/yarn.lock
Labels: Refactor, FE

#119 [FE] 개발용 proxy 설정
  webapp/package-lock.json
  webapp/package.json
  webapp/src/api/core/index.js
  webapp/src/constant/api.js
Labels: Bug, FE

#124 [FE] 토스트 알람 및 데이터 요청 이후 성공/에러 메세지 파싱
  webapp/src/App.jsx
  webapp/src/api/auth.js
  webapp/src/api/comment.js
  webapp/src/api/core/responseHandler.js
  webapp/src/api/core/rootApiInstance.js
  webapp/src/api/team.js
  webapp/src/api/upload.js
  webapp/src/api/user.js
  webapp/src/assets/check.svg
  webapp/src/assets/error.svg
  webapp/src/assets/info.svg
  webapp/src/assets/warning.svg
  webapp/src/components/ComentContainer/Hoc/Hoc.LoadingCommentList.jsx
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/NonLoginNav.jsx
  webapp/src/components/GlobalNavigation/UserInfoDropdown.jsx
  webapp/src/components/GlobalNavigation/index.jsx
  webapp/src/components/GlobalNavigation/style.js
  webapp/src/components/ToastNotification/index.jsx
  webapp/src/components/ToastNotification/style.js
  webapp/src/constant/api.js
  webapp/src/constant/serverStatus.js
  webapp/src/contexts/Comment/useCommentApi.js
  webapp/src/contexts/ToastNotification/action.js
  webapp/src/contexts/ToastNotification/index.js
  webapp/src/contexts/ToastNotification/reducer.js
  webapp/src/contexts/ToastNotification/type.js
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hoc/WithLoading.jsx
  webapp/src/hooks/useAxios.js
  webapp/src/hooks/useIntersect.js
  webapp/src/index.js
  webapp/src/layouts/App/style.js
  webapp/src/layouts/index.js
  webapp/src/layouts/style.js
  webapp/src/mocks/comment/index.js
  webapp/src/mocks/mockUtils.js
  webapp/src/mocks/user/index.js
Labels: Feat, FE

#127 [FE] 마크다운 경고 콘솔문제 해결 및 http-proxy-middleware 설정
  webapp/package-lock.json
  webapp/package.json
  webapp/src/api/core/responseHandler.js
  webapp/src/components/MdEditor/index.jsx
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/NewTeamPost/style.js
  webapp/src/setupProxy.js
Labels: Fix, FE

#129 유저 필수정보 입력 로직 수정 및 최초 로그인 유저 체크 로직 추가
  src/main/generated/com/projectmatching/app/domain/team/entity/QTeamTech.java
  src/main/generated/com/projectmatching/app/domain/techStack/entity/QTechCode.java
  src/main/generated/com/projectmatching/app/domain/techStack/entity/QTechStack.java
  src/main/generated/com/projectmatching/app/domain/user/entity/QUser.java
  src/main/java/com/projectmatching/app/controller/user/UserEditController.java
  src/main/java/com/projectmatching/app/controller/user/UserSignController.java
  src/main/java/com/projectmatching/app/domain/user/QUserRepository.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserEssentialDto.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserIsFirstDto.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserLoginResDto.java
  src/main/java/com/projectmatching/app/domain/user/entity/User.java
  src/main/java/com/projectmatching/app/service/user/Impl/UserSignInService.java
  src/main/java/com/projectmatching/app/service/user/Impl/UserSignUpService.java
  src/test/java/com/projectmatching/app/service/user/UserIsFisrtLoginTest.java
  src/test/java/com/projectmatching/app/service/user/UserSignUpServiceTest.java
Labels: BE

#128 [FE] 회원가입 / 로그인 / 로그아웃 서버연결 확인 후 필수정보 입력 페이지 로직 변경.
  webapp/package.json
  webapp/src/api/auth.js
  webapp/src/components/GlobalNavigation/UserInfoDropdown.jsx
  webapp/src/constant/api.js
  webapp/src/constant/index.js
  webapp/src/mocks/auth/index.js
  webapp/src/mocks/auth/mockMyData.js
  webapp/src/pages/EditUserProfile/EditUserProfileForm.jsx
  webapp/src/pages/EditUserProfile/index.jsx
  webapp/src/pages/EssentialInfo/BelongTeam.jsx
  webapp/src/pages/EssentialInfo/ImgPortfolio.jsx
  webapp/src/pages/EssentialInfo/Skill.jsx
  webapp/src/pages/EssentialInfo/index.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/service/auth.js
Labels: Feat, FE

#131 [FE] storybook 설치 및 theme 설정
  webapp/.eslintrc
  webapp/.storybook/main.js
  webapp/.storybook/preview.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/assets/icons/check.svg
  webapp/src/assets/icons/error.svg
  webapp/src/assets/icons/info.svg
  webapp/src/assets/icons/warning.svg
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/LoginNavigation.stories.jsx
  webapp/src/components/GlobalNavigation/NonLoginNavigation.stories.jsx
  webapp/src/index.js
  webapp/src/styles/GlobalStyles.js
  webapp/src/styles/Normalize.js
  webapp/src/styles/index.jsx
  webapp/src/styles/theme.js
Labels: Feat, FE

#138 [FE] 회원가입 페이지 디자인 및 기능수정
  webapp/src/App.jsx
  webapp/src/api/auth.js
  webapp/src/assets/icons/conect-main.svg
  webapp/src/assets/images/apple-logo.png
  webapp/src/assets/images/google-logo.png
  webapp/src/components/CardsGrid/index.jsx
  webapp/src/components/Common/Button/Button.stories.jsx
  webapp/src/components/Common/Button/index.jsx
  webapp/src/components/Common/Button/style.js
  webapp/src/components/Common/Divider/index.jsx
  webapp/src/components/Common/Divider/style.js
  webapp/src/components/Common/Form/index.jsx
  webapp/src/components/Common/Input/Input.stories.jsx
  webapp/src/components/Common/Input/index.jsx
  webapp/src/components/Common/Input/style.js
  webapp/src/components/Common/Loader/index.jsx
  webapp/src/components/Common/Select/index.jsx
  webapp/src/components/Common/Tabs/index.jsx
  webapp/src/components/Common/Tabs/style.js
  webapp/src/components/SocialLoginButtons/SocialLoginButtons.stories.jsx
  webapp/src/components/SocialLoginButtons/SocialLoginButtons.style.js
  webapp/src/components/SocialLoginButtons/index.jsx
  webapp/src/constant/api.js
  webapp/src/constant/service.constant.js
  webapp/src/hooks/useForm.js
  webapp/src/layouts/style.js
  webapp/src/mocks/auth/index.js
  webapp/src/pages/Callback/index.jsx
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/SignUp/IdPassword.jsx
  webapp/src/pages/SignUp/SignUp.stories.jsx
  webapp/src/pages/SignUp/SignUp.style.js
  webapp/src/pages/SignUp/index.jsx
  webapp/src/pages/SignUp/style.js
  webapp/src/service/login.validation.js
  webapp/src/service/signUp.validation.js
  webapp/src/styles/mixin.js
  webapp/src/styles/theme.js
  webapp/src/utils/customProptypes.js
Labels: Refactor, FE, Design

#139 [FE] storybook 배포 스크립트 설정 및 github action 설정
  .github/workflows/chromatic.yml
  .gitignore
  webapp/.gitignore
  webapp/build-storybook.log
  webapp/package-lock.json
  webapp/package.json
Labels: Document, FE

#141 [FE] storybook 정적 배포 github action 연결
  .github/workflows/chromatic.yml
  .gitignore
  webapp/.gitignore
  webapp/build-storybook.log
  webapp/package-lock.json
  webapp/package.json
Labels: Document, FE, Design

#144 [FE] GNB css
  webapp/src/assets/icons/alarm.svg
  webapp/src/assets/icons/info.svg
  webapp/src/assets/icons/logo.svg
  webapp/src/assets/icons/nav-logo.svg
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/LoginNavigation.stories.jsx
  webapp/src/components/GlobalNavigation/NonLoginNav.jsx
  webapp/src/components/GlobalNavigation/style.js
  webapp/src/mocks/skills/Image/c++.svg
  webapp/src/mocks/skills/Image/javascript.svg
  webapp/src/styles/theme.js
Labels: FE, Design

#147 [FE] userCard css
  webapp/src/assets/icons/chat.svg
  webapp/src/assets/icons/check-button.svg
  webapp/src/assets/icons/cross-button.svg
  webapp/src/assets/icons/heart.svg
  webapp/src/assets/icons/left-skill.svg
  webapp/src/assets/icons/right-skill.svg
  webapp/src/assets/icons/view.svg
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/style.js
  webapp/src/components/UserCard/UserCard.stories.jsx
  webapp/src/components/UserCard/index.jsx
  webapp/src/components/UserCard/style.js
  webapp/src/mocks/teckStack/Image/apple.png
  webapp/src/mocks/teckStack/Image/javascript.png
  webapp/src/mocks/teckStack/index.js
  webapp/src/mocks/teckStack/skillsImg.js
  webapp/src/styles/theme.js
Labels: Feat, Fix, FE, Design

#148 [FE] teamCard css
  webapp/src/assets/icons/chat.svg
  webapp/src/assets/icons/heart.svg
  webapp/src/assets/icons/view.svg
  webapp/src/components/TeamCard/TeamCard.stories.jsx
  webapp/src/components/TeamCard/index.jsx
  webapp/src/components/TeamCard/style.js
Labels: Feat, FE, Design

#150 [FE] Single Select 컴포넌트 & Multi Select 컴포넌트 구현
  webapp/src/assets/icons/left-skill.svg
  webapp/src/assets/icons/right-skill.svg
  webapp/src/components/Common/Divider/Divider.style.js
  webapp/src/components/Common/Divider/index.jsx
  webapp/src/components/Common/SelectInput/MultiPlaceHolder.jsx
  webapp/src/components/Common/SelectInput/SelectInput.stories.jsx
  webapp/src/components/Common/SelectInput/SelectInput.style.js
  webapp/src/components/Common/SelectInput/SinglePlaceHolder.jsx
  webapp/src/components/Common/SelectInput/index.jsx
  webapp/src/constant/index.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hooks/useDropdown.js
  webapp/src/mocks/teckStack/Image/apple.png
  webapp/src/mocks/teckStack/Image/javascript.png
  webapp/src/mocks/teckStack/index.js
  webapp/src/mocks/teckStack/skillsImg.js
  webapp/src/pages/EssentialInfo/SubPages/Skills.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/service/essentialForm.validation.js
  webapp/src/styles/GlobalStyles.js
  webapp/src/styles/theme.js
Labels: Feat, FE, Design

#153 [FE] teamBoard - css
  webapp/src/assets/icons/chat.svg
  webapp/src/assets/icons/heart.svg
  webapp/src/assets/icons/view.svg
  webapp/src/components/CardsGrid/style.js
  webapp/src/components/Common/Image/index.jsx
  webapp/src/components/Common/Image/style.js
  webapp/src/components/Common/ProfileImg/index.jsx
  webapp/src/components/Common/ProfileImg/style.js
  webapp/src/components/GlobalNavigation/style.js
  webapp/src/components/TeamCard/index.jsx
  webapp/src/components/TeamCard/style.js
  webapp/src/mocks/teamHandler.mock/teamsList.js
  webapp/src/pages/TeamBoard/TeamBoard.stories.jsx
  webapp/src/pages/TeamBoard/style.js
Labels: FE, Design

#156 [FE] AssignPage - Delete GNB
  webapp/src/App.jsx
  webapp/src/layouts/layout.js
  webapp/src/layouts/layoutAssign.js
Labels: Fix, FE

#158 [FE] 유저필수정보입력 api연결 + 유저필수정보입력 모달 형식 수정
  webapp/src/App.jsx
  webapp/src/api/auth.api.js
  webapp/src/api/instance/privateApiInstance.js
  webapp/src/api/user.api.js
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/components/Common/Image/index.jsx
  webapp/src/components/Common/SelectInput/PlaceHolder/MultiPlaceHolder.jsx
  webapp/src/components/Common/SelectInput/PlaceHolder/SinglePlaceHolder.jsx
  webapp/src/components/Common/SelectInput/index.jsx
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/LoginNavigation.stories.jsx
  webapp/src/components/GlobalNavigation/NonLoginNav.jsx
  webapp/src/components/GlobalNavigation/UserInfoDropdown.jsx
  webapp/src/components/GlobalNavigation/index.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.style.js
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/constant/index.js
  webapp/src/constant/route.constant.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hoc/withProvider.jsx
  webapp/src/hooks/useFileInput.js
  webapp/src/hooks/useFileUploader.js
  webapp/src/hooks/useForm.js
  webapp/src/hooks/useUserInfo.js
  webapp/src/layouts/layout.js
  webapp/src/layouts/layoutAssign.js
  webapp/src/mocks/authHandler.mock/index.js
  webapp/src/mocks/etcHandler.mock/skill.mock.js
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileForm.jsx
  webapp/src/pages/EssentialInfo/EssentialInfo.stories.jsx
  webapp/src/pages/EssentialInfo/EssentialInfo.style.js
  webapp/src/pages/EssentialInfo/SubPages/EssentialCallback.jsx
  webapp/src/pages/EssentialInfo/SubPages/ProfileImage.jsx
  webapp/src/pages/EssentialInfo/SubPages/Skills.jsx
  webapp/src/pages/EssentialInfo/index.jsx
  webapp/src/pages/Login/Login.stories.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/MyPost/index.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/SignUp/SignUp.stories.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/UserBoard/index.jsx
  webapp/src/service/auth.js
  webapp/src/service/auth.parser.js
  webapp/src/service/essentialForm.validation.js
  webapp/src/service/skillStack.parser.js
  webapp/src/types/techSkill.type.js
  webapp/src/types/user.type.js
Labels: Feat, FE

#162 [FE] 커스텀 에러 추가 및 Auth 관련 에러처리
  webapp/src/api/instance/responseHandler.js
  webapp/src/components/ComentContainer/CommentForm/Create.Reply.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Root.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Edit.CommentForm.jsx
  webapp/src/components/Common/BackButton/index.jsx
  webapp/src/components/GlobalNavigation/UserInfoDropdown.jsx
  webapp/src/components/ImageUploader/index.jsx
  webapp/src/components/ToastNotification/ToastNotification.style.js
  webapp/src/contexts/Comment/useCommentApi.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hoc/WithLoading.jsx
  webapp/src/hooks/useAxios.js
  webapp/src/hooks/useFileUploader.js
  webapp/src/hooks/useUserInfo.js
  webapp/src/mocks/authHandler.mock/mockMyData.js
  webapp/src/mocks/commentHandler.mock/index.js
  webapp/src/mocks/teamHandler.mock/index.js
  webapp/src/mocks/userHandler.mock/essentialInfo.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/pages/Callback/ApiErrorCallback.jsx
  webapp/src/pages/Callback/AuthErrorCallback.jsx
  webapp/src/pages/Callback/index.jsx
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileForm.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/service/auth.js
  webapp/src/utils/customError.js
Labels: Feat, FE

#163 [FE] 유저프로필 페이지 css + api요청 (+ 마크다운 라이브러리 변경)
  webapp/package-lock.json
  webapp/package.json
  webapp/src/api/user.api.js
  webapp/src/components/Common/SelectInput/PlaceHolder/MultiPlaceHolder.jsx
  webapp/src/components/Common/SelectInput/PlaceHolder/SinglePlaceHolder.jsx
  webapp/src/components/Common/SelectInput/SelectInput.style.js
  webapp/src/components/Common/SelectInput/index.jsx
  webapp/src/components/Common/TextInput/TextInput.style.js
  webapp/src/components/Common/TextInput/index.jsx
  webapp/src/components/MarkdownEditor/MarkdownEditor.style.js
  webapp/src/components/MarkdownEditor/index.jsx
  webapp/src/components/MdEditor/index.jsx
  webapp/src/components/MdViewer/index.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.style.js
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/constant/index.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hooks/useAxios.js
  webapp/src/hooks/useCheckNicknameDuplicate.js
  webapp/src/hooks/useFileUploader.js
  webapp/src/layouts/style.js
  webapp/src/mocks/userHandler.mock/essentialInfo.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/pages/Callback/index.jsx
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditUserProfile/EditUserProfile.style.js
  webapp/src/pages/EditUserProfile/EditUserProfile.view.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileDetail.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileForm.jsx
  webapp/src/pages/EditUserProfile/index.jsx
  webapp/src/pages/EditUserProfile/style.js
  webapp/src/pages/EssentialInfo/SubPages/BelongTeam.jsx
  webapp/src/pages/EssentialInfo/SubPages/SessionJob.jsx
  webapp/src/pages/EssentialInfo/SubPages/Skills.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/service/auth.parser.js
  webapp/src/service/user.parser.js
  webapp/src/service/user.validation.js
  webapp/src/types/user.type.js
Labels: Feat, FE, Design
