Repository yulpumta-clone-team/Co-nect, pull requests merged in 2022-12, with the labels that each got.

#227 [FE] 기술스택 목록 프론트 assets으로 관리
  webapp/src/assets/images/techskillls/100-js.png
  webapp/src/assets/images/techskillls/101-react.png
  webapp/src/assets/images/techskillls/102-vue.png
  webapp/src/assets/images/techskillls/103-angular.png
  webapp/src/assets/images/techskillls/104-svelte.png
  webapp/src/assets/images/techskillls/105-ts.png
  webapp/src/assets/images/techskillls/106-nextjs.png
  webapp/src/assets/images/techskillls/200-nodejs.png
  webapp/src/assets/images/techskillls/201-nestjs.png
  webapp/src/assets/images/techskillls/202-express.png
  webapp/src/assets/images/techskillls/203-java.png
  webapp/src/assets/images/techskillls/204-spring.png
  webapp/src/assets/images/techskillls/205-c.png
  webapp/src/assets/images/techskillls/206-cpp.png
  webapp/src/assets/images/techskillls/207-cs.png
  webapp/src/assets/images/techskillls/208-python.png
  webapp/src/assets/images/techskillls/209-django.png
  webapp/src/assets/images/techskillls/210-go.png
  webapp/src/assets/images/techskillls/211-php.png
  webapp/src/assets/images/techskillls/300-flutter.png
  webapp/src/assets/images/techskillls/301-reactnative.png
  webapp/src/assets/images/techskillls/302-kotlin.png
  webapp/src/assets/images/techskillls/303-swift.png
  webapp/src/assets/images/techskillls/500-mysql.png
  webapp/src/assets/images/techskillls/501-h2.png
  webapp/src/assets/images/techskillls/502-mongodb.png
  webapp/src/assets/images/techskillls/503-oracle.png
  webapp/src/assets/images/techskillls/600-git.png
  webapp/src/assets/images/techskillls/601-docker.png
  webapp/src/assets/images/techskillls/602-kubernetes.png
  webapp/src/assets/images/techskillls/603-aws.png
  webapp/src/assets/images/techskillls/604-jest.png
  webapp/src/assets/images/techskillls/605-cypress.png
  webapp/src/components/TechSkills/TechSkills.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackOptions.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectedViewer.jsx
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/constant/index.js
  webapp/src/constant/techskill.constant.js
Labels: Fix, FE

#230 [FE] styled-component 디버깅을 위한 styled-component/macro 적용
  webapp/src/assets/fonts/index.js
  webapp/src/assets/icons/icons.stories.jsx
  webapp/src/components/CardsGrid/CardsGrid.style.js
  webapp/src/components/CheckBox/style.js
  webapp/src/components/ComentContainer/style.js
  webapp/src/components/Common/BackButton/BackButton.style.js
  webapp/src/components/Common/Button/Button.stories.jsx
  webapp/src/components/Common/Button/Button.style.js
  webapp/src/components/Common/CheckInput/CheckInput.stories.jsx
  webapp/src/components/Common/CheckInput/CheckInput.style.js
  webapp/src/components/Common/Divider/Divider.style.js
  webapp/src/components/Common/Dropdown/style.js
  webapp/src/components/Common/Image/style.js
  webapp/src/components/Common/Like/style.js
  webapp/src/components/Common/SelectInput/SelectInput.style.js
  webapp/src/components/Common/Tabs/style.js
  webapp/src/components/Common/TextArea/TextArea.style.js
  webapp/src/components/Common/TextInput/TextInput.style.js
  webapp/src/components/Common/UpperButton/UpperButton.style.js
  webapp/src/components/Common/WindowModal/style.js
  webapp/src/components/GlobalNavigation/style.js
  webapp/src/components/MarkdownEditor/MarkdownEditor.style.js
  webapp/src/components/ProfileImg/style.js
  webapp/src/components/SocialLoginButtons/SocialLoginButtons.style.js
  webapp/src/components/TeamBelongCheckInput/TeamBelongCheckInput.style.js
  webapp/src/components/TeamCard/TeamCard.style.js
  webapp/src/components/TechSkills/TechSkills.style.js
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.style.js
  webapp/src/components/ToastNotification/ToastNotification.style.js
  webapp/src/components/UserCard/UserCard.style.js
  webapp/src/layouts/layout.style.js
  webapp/src/pages/Callback/callback.style.js
  webapp/src/pages/EditTeamPost/EditTeamPost.style.js
  webapp/src/pages/EditUserProfile/EditUserProfile.style.js
  webapp/src/pages/EssentialInfo/EssentialInfo.style.js
  webapp/src/pages/Login/Login.style.js
  webapp/src/pages/Main/style.js
  webapp/src/pages/MyList/style.js
  webapp/src/pages/MyPost/style.js
  webapp/src/pages/NewTeamPost/NewTeamPost.style.js
  webapp/src/pages/SignUp/SignUp.style.js
  webapp/src/pages/TeamBoard/style.js
  webapp/src/pages/TeamPost/TeamPost.style.js
  webapp/src/pages/UserBoard/style.js
  webapp/src/pages/UserPost/UserPost.style.js
  webapp/src/styles/GlobalStyles.js
  webapp/src/styles/Normalize.js
  webapp/src/styles/index.jsx
  webapp/src/styles/mixin.js
  webapp/src/styles/theme.js
Labels: FE, Chore

#223 Feat/oauth #222 이슈 수정
  build.gradle
  src/main/java/com/projectmatching/app/config/SwaggerConfiguration.java
  src/main/java/com/projectmatching/app/config/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/projectmatching/app/config/resTemplate/ResponseTemplate.java
  src/main/java/com/projectmatching/app/controller/user/UserEditController.java
  src/main/java/com/projectmatching/app/controller/user/UserSignController.java
  src/main/java/com/projectmatching/app/domain/Validatable.java
  src/main/java/com/projectmatching/app/domain/user/UserProfile.java
  src/main/java/com/projectmatching/app/domain/user/UserRepository.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserDto.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserEssentialDto.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserInfo.java
  src/main/java/com/projectmatching/app/domain/user/dto/UserInfoDto.java
  src/main/java/com/projectmatching/app/domain/user/entity/User.java
  src/main/java/com/projectmatching/app/service/user/Impl/UserService.java
  src/main/java/com/projectmatching/app/service/user/Impl/UserSignInService.java
  src/main/java/com/projectmatching/app/service/user/Impl/UserSignUpService.java
  src/main/java/com/projectmatching/app/service/user/OAuthService.java
  src/main/java/com/projectmatching/app/service/userInfoAdder/UserInfoAdderServiceImpl.java
  src/main/java/com/projectmatching/app/util/AuthTokenProvider.java
  src/main/java/com/projectmatching/app/util/filter/JwtAuthFilter.java
  src/main/java/com/projectmatching/app/util/filter/JwtExceptionFilter.java
  src/test/java/com/projectmatching/app/acceptance/aspect/UserInfoDtoContainTest.java
  src/test/java/com/projectmatching/app/service/jwt/JwtServiceTest.java
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hooks/useHandleLogin.js
  webapp/src/hooks/useUserInfo.js
  webapp/src/pages/OAuthCallback/index.jsx
Labels: Fix, FE, BE

#231 [FE] 무한스크롤 버그 수정 및 유저 및 팀 보드 비었을 때 유도 UI추가
  webapp/src/components/CardsGrid/CardsGrid.style.js
  webapp/src/components/CardsGrid/index.jsx
  webapp/src/constant/service.constant.js
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hooks/useIntersect.js
  webapp/src/pages/TeamBoard/TeamBoard.stories.jsx
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/UserBoard/UserBoard.stories.jsx
  webapp/src/pages/UserBoard/index.jsx
Labels: Bug, FE

#234 [FE] 스타일 세부적인 내용수정
  webapp/public/index.html
  webapp/public/main-logo.png
  webapp/src/components/Common/SelectInput/index.jsx
  webapp/src/components/PostInfo/PostInfo.style.js
  webapp/src/components/PostInfo/index.jsx
  webapp/src/components/TeamBelongCheckInput/TeamBelongCheckInput.style.js
  webapp/src/components/TeamBelongCheckInput/index.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectedViewer.jsx
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hooks/useDropdown.js
  webapp/src/layouts/layout.style.js
  webapp/src/mocks/userHandler.mock/userDetail.js
  webapp/src/pages/Callback/callback.style.js
  webapp/src/pages/EditUserProfile/EditUserProfile.style.js
  webapp/src/pages/EditUserProfile/EditUserProfile.view.jsx
  webapp/src/pages/MyPost/MyPost.style.js
  webapp/src/pages/MyPost/index.jsx
  webapp/src/pages/MyPost/style.js
  webapp/src/pages/NewTeamPost/NewTeamPost.style.js
  webapp/src/pages/NotAllow/NotAllow.stories.jsx
  webapp/src/pages/NotAllow/index.jsx
  webapp/src/pages/NotFound/ NoutFound.stories.jsx
  webapp/src/pages/NotFound/index.jsx
  webapp/src/pages/OAuthFail/OauthFail.stories.jsx
  webapp/src/pages/OAuthFail/index.jsx
  webapp/src/pages/TeamPost/TeamPost.style.js
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/UserPost/UserPost.style.js
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/service/team/team.parser.js
  webapp/src/service/user/user.parser.js
  webapp/src/types/user.type.js
  webapp/src/types/user.typedef.js
Labels: Fix, FE, Chore

#229 [FE] Main Page 1차 css 완성
  webapp/src/assets/images/board-link.png
  webapp/src/assets/images/cloud.png
  webapp/src/assets/images/conect-mainpage.png
  webapp/src/assets/images/dating-place.png
  webapp/src/assets/images/earth.png
  webapp/src/assets/images/feedback-message.png
  webapp/src/assets/images/ghost.png
  webapp/src/assets/images/main-gradient.png
  webapp/src/assets/images/post-link.png
  webapp/src/assets/images/screen-image.png
  webapp/src/assets/images/section2-bg.png
  webapp/src/assets/images/signup-link.png
  webapp/src/constant/main.constant.jsx
  webapp/src/contexts/ToastNotification/index.js
  webapp/src/pages/Main/Main.stories.jsx
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/Main/style.js
  webapp/src/router/PublicRoutes.js
  webapp/src/router/index.jsx
  webapp/src/styles/theme.js
Labels: FE, Design

#238 [FE] Main Page Animation 적용
  webapp/package-lock.json
  webapp/package.json
  webapp/src/constant/main.constant.jsx
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/Main/style.js
Labels: FE, Design

#244 [FE]readMe docs - 프로젝트 소개 및 팀원 소개
  README.md
Labels: Document

#246 [FE] 이미지 관련 src를 s3로 관리하는 것과 assets으로 관리하는 것으로 구분!
  webapp/src/api/user.api.js
  webapp/src/components/Common/Image/index.jsx
  webapp/src/components/Common/ProfileImg/ProfileImg.style.js
  webapp/src/components/Common/ProfileImg/index.jsx
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/NonLoginNav.jsx
  webapp/src/components/SocialLoginButtons/index.jsx
  webapp/src/components/TeamCard/index.jsx
  webapp/src/components/TechStackSelectInput/TechStackOptions.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.stories.jsx
  webapp/src/components/TechStackSelectInput/TechStackSelectInput.style.js
  webapp/src/components/TechStackSelectInput/TechStackSelectedViewer.jsx
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/components/UserCard/index.jsx
  webapp/src/constant/api.constant.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hoc/SimpleListComponent.jsx
  webapp/src/hooks/useAuthService.js
  webapp/src/mocks/etcHandler.mock/skill.mock.js
  webapp/src/pages/EditTeamPost/EditTeamPost.style.js
  webapp/src/pages/EditTeamPost/EditTeamPost.view.jsx
  webapp/src/pages/EditTeamPost/EditTeamPostDetail.jsx
  webapp/src/pages/EditUserProfile/EditUserProfileDetail.jsx
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/service/user/user.parser.js
  webapp/src/utils/index.js
Labels: Bug, FE
