Repository yulpumta-clone-team/Co-nect, pull requests merged in 2022-07, with the labels that each got.

#73 [FE] redux 로직 덜어내기
  webapp/src/_actions/global_action.js
  webapp/src/_reducers/global_reducer.js
  webapp/src/_reducers/index.js
  webapp/src/_types/globalTypes.js
  webapp/src/components/ErrorModal/index.jsx
  webapp/src/components/Navigation/LoginNav.jsx
  webapp/src/components/Potal/index.jsx
  webapp/src/components/WindowModal/Potal.jsx
  webapp/src/components/WindowModal/index.jsx
  webapp/src/components/WindowModal/style.js
  webapp/src/hooks/usePopup.js
  webapp/src/index.js
  webapp/src/layouts/App/index.js
  webapp/src/pages/EditTeamPost/index.jsx
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/NewTeamPost/index.jsx
Labels: Refactor, FE

#75 [FE] api 변수 관리 및 빌드 환경에 따른 uri 설정
  webapp/package-lock.json
  webapp/package.json
  webapp/src/api/auth.js
  webapp/src/api/comment.js
  webapp/src/api/core/index.js
  webapp/src/api/team.js
  webapp/src/api/user.js
  webapp/src/apiAction/auth.js
  webapp/src/apiAction/comment.js
  webapp/src/apiAction/team.js
  webapp/src/apiAction/user.js
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/constant/api.js
  webapp/src/constant/route.js
  webapp/src/layouts/App/index.js
  webapp/src/mocks/auth/index.js
  webapp/src/mocks/handlers.js
  webapp/src/mocks/team/index.js
  webapp/src/mocks/user/index.js
  webapp/src/pages/EditTeamPost/index.jsx
  webapp/src/pages/EditUserProfile/index.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/TeamPost/index.jsx
  webapp/src/pages/UserBoard/index.jsx
  webapp/src/pages/UserPost/index.jsx
Labels: Refactor, FE

#84 [FE] 댓글 mock데이터 추가 및 api 로직 수정
  webapp/src/api/comment.js
  webapp/src/apiAction/comment.js
  webapp/src/components/ComentContainer/Comment.jsx
  webapp/src/components/ComentContainer/CommentForm.jsx
  webapp/src/components/ComentContainer/CommentList.jsx
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/mocks/comment/index.js
  webapp/src/mocks/team/teamComments.js
  webapp/src/mocks/user/userComments.js
Labels: Refactor, FE

#86 [FE] UserBoard, TeamBoard 페이지 무한스크롤 버그 수정
  webapp/src/api/team.js
  webapp/src/api/user.js
  webapp/src/components/TeamCard/index.jsx
  webapp/src/hooks/useInfinitiScroll.js
  webapp/src/hooks/useIntersect.js
  webapp/src/mocks/team/index.js
  webapp/src/mocks/team/teamsList.js
  webapp/src/mocks/user/index.js
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/UserBoard/index.jsx
Labels: Fix, FE

#91 [FE] 데이터 요청(GET) 이후 로직(로딩, 에러)을 선언적으로 처리하는 컴포넌트
  webapp/src/api/team.js
  webapp/src/api/user.js
  webapp/src/components/Common/Dropdown/index.jsx
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hoc/WithLoading.jsx
  webapp/src/hooks/useAxios.js
  webapp/src/hooks/useIntersect.js
  webapp/src/mocks/mockUtils.js
  webapp/src/mocks/team/index.js
  webapp/src/mocks/user/index.js
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditTeamPost/index.jsx
  webapp/src/pages/EditTeamPost/style.js
  webapp/src/pages/EditUserProfile/EdiitUserProfileForm.jsx
  webapp/src/pages/EditUserProfile/index.jsx
  webapp/src/pages/EditUserProfile/style.js
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/MyPost/index.jsx
  webapp/src/pages/MyUserList/Cards.jsx
  webapp/src/pages/MyUserList/index.jsx
  webapp/src/pages/MyUserList/style.js
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/TeamPost/index.jsx
  webapp/src/pages/TeamPost/style.js
  webapp/src/pages/UserBoard/index.jsx
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/pages/UserPost/index.jsx
  webapp/src/pages/UserPost/style.js
Labels: Feat, FE

#100 [FE] api 요청 url에 prefix 추가
  webapp/src/api/auth.js
  webapp/src/api/comment.js
  webapp/src/api/core/index.js
  webapp/src/api/team.js
  webapp/src/api/upload.js
  webapp/src/api/user.js
  webapp/src/constant/api.js
  webapp/src/mocks/auth/index.js
  webapp/src/mocks/comment/index.js
  webapp/src/mocks/team/index.js
  webapp/src/mocks/user/index.js
Labels: Fix, FE

#97 [FE] Fix: Login화면 Modal형식으로 전환 + EditUser/TeamProfile
  webapp/src/pages/EditTeamPost/EditTeamForm.jsx
  webapp/src/pages/EditUserProfile/EdiitUserProfileForm.jsx
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/Login/style.js
  webapp/src/pages/NewTeamPost/index.jsx
  webapp/src/pages/SignUp/index.jsx
Labels: Fix, FE
