Repository yulpumta-clone-team/Co-nect, pull requests merged in 2023-01, with the labels that each got.

#247 [FE] ReadMe docs - 위키 테이블 생성
  README.md
Labels: Document

#250 [DOCS] board관련 gif 수정 했습니다.
  README.md
Labels: Document, Chore

#253 Develop branch readMe 위키 테이블 수정
  README.md
Labels: Document

#256 [FE] hooks form 버그 수정
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Common/Tabs/Tabs.stories.jsx
  webapp/src/components/Common/Tabs/Tabs.style.js
  webapp/src/components/Common/Tabs/index.jsx
  webapp/src/components/TechStackSelectInput/index.jsx
  webapp/src/constant/index.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hoc/WithLoading.jsx
  webapp/src/hooks/useForm.js
  webapp/src/mocks/teamHandler.mock/index.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/mocks/userHandler.mock/myPosts.js
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/MyList/MyList.style.js
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/MyList/style.js
  webapp/src/pages/MyPost/index.jsx
  webapp/src/pages/TeamBoard/TeamBoard.style.js
  webapp/src/pages/TeamBoard/index.jsx
  webapp/src/pages/TeamPost/TeamPostDetail.jsx
  webapp/src/pages/UserBoard/UserBoard.style.js
  webapp/src/pages/UserBoard/index.jsx
  webapp/src/pages/UserPost/UserPostDetail.jsx
  webapp/src/service/auth/auth.validation.js
  webapp/src/service/user/user.parser.js
  webapp/src/utils/index.js
Labels: Bug, Fix, FE

#257 [FE] css team post 비율 수정 + back button 위치 수정
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/TeamPost/TeamPost.style.js
Labels: Fix, Design

#258 [FE] 무한스크롤 로딩 동작 수정
  webapp/src/components/CardsGrid/index.jsx
  webapp/src/hoc/WithInfiniteScroll.jsx
Labels: Bug, FE

#259 [FE] Desktop 기준 레이아웃 css 모든 버그 수정
  README.md
  webapp/src/components/CardsGrid/index.jsx
  webapp/src/components/Common/Like/index.jsx
  webapp/src/components/Common/Loader/CardLoader/CardLoader.style.js
  webapp/src/components/Footer/Footer.stories.jsx
  webapp/src/components/Footer/Footer.style.js
  webapp/src/components/Footer/index.jsx
  webapp/src/components/GlobalNavigation/GlobalNavigation.style.js
  webapp/src/components/GlobalNavigation/LoginNav.jsx
  webapp/src/components/GlobalNavigation/LoginNavigation.stories.jsx
  webapp/src/components/GlobalNavigation/NonLoginNav.jsx
  webapp/src/components/GlobalNavigation/NonLoginNavigation.stories.jsx
  webapp/src/components/GlobalNavigation/UserInfoDropdown.jsx
  webapp/src/components/GlobalNavigation/index.jsx
  webapp/src/components/SocialLoginButtons/SocialLoginButtons.style.js
  webapp/src/components/SocialLoginButtons/index.jsx
  webapp/src/components/UserCard/UserCard.style.js
  webapp/src/constant/main.constant.js
  webapp/src/constant/route.constant.js
  webapp/src/contexts/EssentialForm/useEssentialForm.js
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hooks/useCheckUserDuplicate.js
  webapp/src/hooks/useForm.js
  webapp/src/hooks/useIntersect.js
  webapp/src/layouts/LayoutFullPage.jsx
  webapp/src/layouts/LayoutWithHeader.jsx
  webapp/src/layouts/layout.style.js
  webapp/src/mocks/authHandler.mock/index.js
  webapp/src/mocks/commentHandler.mock/index.js
  webapp/src/mocks/etcHandler.mock/index.js
  webapp/src/mocks/mockUtils.js
  webapp/src/mocks/teamHandler.mock/index.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/pages/EssentialInfo/SubPages/Nickname.jsx
  webapp/src/pages/EssentialInfo/SubPages/Slogan.jsx
  webapp/src/pages/Login/Login.style.js
  webapp/src/pages/Login/index.jsx
  webapp/src/pages/Main/Main.style.js
  webapp/src/pages/Main/index.jsx
  webapp/src/pages/MyList/MyList.style.js
  webapp/src/pages/MyList/index.jsx
  webapp/src/pages/MyPost/MyPost.style.js
  webapp/src/pages/NotAllow/index.jsx
  webapp/src/pages/SignUp/index.jsx
  webapp/src/pages/TeamBoard/TeamBoard.style.js
  webapp/src/pages/UserBoard/UserBoard.style.js
  webapp/src/router/PrivateRoutes.js
  webapp/src/router/PublicRoutes.js
  webapp/src/router/index.jsx
  webapp/src/service/auth/auth.validation.js
  webapp/src/service/user/user.validation.js
  webapp/src/styles/animation.js
Labels: Bug, FE, Design

#261 [FE] mock api를 활용한 데모 버전 github action 생성
  .github/workflows/chromatic.yml
  .github/workflows/fe-demo.yml
  README.md
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/CardsGrid/index.jsx
  webapp/src/components/ComentContainer/Comment.style.js
  webapp/src/components/ComentContainer/CommentElement/CommentButtonContainer.jsx
  webapp/src/components/ComentContainer/CommentElement/CommentLikeSvg.jsx
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.stories.jsx
  webapp/src/components/ComentContainer/CommentElement/NestedCommentToggleButton.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.stories.jsx
  webapp/src/components/ComentContainer/CommentElement/Secret.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Reply.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Root.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Edit.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.stories.jsx
  webapp/src/components/ComentContainer/CommentList/Root.CommentList.jsx
  webapp/src/components/ComentContainer/LoadingCommentList.jsx
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/components/Common/ProfileImg/index.jsx
  webapp/src/components/Common/WindowModal/Portal.jsx
  webapp/src/components/Common/WindowModal/index.jsx
  webapp/src/components/Common/WindowModal/style.js
  webapp/src/components/DemoAlert/index.jsx
  webapp/src/components/TeamCard/TeamCard.stories.jsx
  webapp/src/components/UserCard/UserCard.stories.jsx
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hooks/useModal.js
  webapp/src/index.js
  webapp/src/mocks/authHandler.mock/index.js
  webapp/src/mocks/authHandler.mock/mockMyData.js
  webapp/src/mocks/commentHandler.mock/comment.mock.js
  webapp/src/mocks/commentHandler.mock/index.js
  webapp/src/mocks/commentHandler.mock/teamComments.js
  webapp/src/mocks/commentHandler.mock/userComments.js
  webapp/src/mocks/etcHandler.mock/index.js
  webapp/src/mocks/mockUtils.js
  webapp/src/mocks/teamHandler.mock/editTeamDetail.js
  webapp/src/mocks/teamHandler.mock/index.js
  webapp/src/mocks/teamHandler.mock/team.mock.js
  webapp/src/mocks/teamHandler.mock/teamDetail.js
  webapp/src/mocks/teamHandler.mock/teamsList.js
  webapp/src/mocks/userHandler.mock/essentialInfo.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/mocks/userHandler.mock/user.mock.js
  webapp/src/mocks/userHandler.mock/userDetail.js
  webapp/src/mocks/userHandler.mock/usersList.js
  webapp/src/pages/EssentialInfo/EssentialInfo.stories.jsx
  webapp/src/pages/EssentialInfo/SubPages/EssentialCallback.jsx
  webapp/src/pages/NotAllow/index.jsx
  webapp/src/pages/NotFound/ NoutFound.stories.jsx
  webapp/src/pages/TeamBoard/TeamBoard.stories.jsx
  webapp/src/pages/TeamPost/TeamPost.stories.jsx
  webapp/src/pages/UserBoard/UserBoard.stories.jsx
  webapp/src/pages/UserPost/UserPost.stories.jsx
  webapp/src/utils/index.js
Labels: FE, Build

#262 [FE] 데모 및 chromatic 배포 github action 에러 수정
  .github/workflows/chromatic.yml
  .github/workflows/fe-demo.yml
  webapp/src/mocks/commentHandler.mock/index.js
  webapp/src/mocks/teamHandler.mock/team.mock.js
  webapp/src/mocks/userHandler.mock/user.mock.js
Labels: Bug, FE, Build

#263 메인 브랜치 업데이트 - [FE] mock api를 활용한 데모 버전 github action 생성
  .github/workflows/chromatic.yml
  .github/workflows/fe-demo.yml
  README.md
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/CardsGrid/index.jsx
  webapp/src/components/ComentContainer/Comment.style.js
  webapp/src/components/ComentContainer/CommentElement/CommentButtonContainer.jsx
  webapp/src/components/ComentContainer/CommentElement/CommentLikeSvg.jsx
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Nested.CommentElement.stories.jsx
  webapp/src/components/ComentContainer/CommentElement/NestedCommentToggleButton.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentElement/Root.CommentElement.stories.jsx
  webapp/src/components/ComentContainer/CommentElement/Secret.CommentElement.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Reply.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Create.Root.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentForm/Edit.CommentForm.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.jsx
  webapp/src/components/ComentContainer/CommentList/Nested.CommentList.stories.jsx
  webapp/src/components/ComentContainer/CommentList/Root.CommentList.jsx
  webapp/src/components/ComentContainer/LoadingCommentList.jsx
  webapp/src/components/ComentContainer/index.jsx
  webapp/src/components/Common/ProfileImg/index.jsx
  webapp/src/components/Common/WindowModal/Portal.jsx
  webapp/src/components/Common/WindowModal/index.jsx
  webapp/src/components/Common/WindowModal/style.js
  webapp/src/components/DemoAlert/index.jsx
  webapp/src/components/TeamCard/TeamCard.stories.jsx
  webapp/src/components/UserCard/UserCard.stories.jsx
  webapp/src/hoc/WithInfiniteScroll.jsx
  webapp/src/hooks/useModal.js
  webapp/src/index.js
  webapp/src/mocks/authHandler.mock/index.js
  webapp/src/mocks/authHandler.mock/mockMyData.js
  webapp/src/mocks/commentHandler.mock/comment.mock.js
  webapp/src/mocks/commentHandler.mock/index.js
  webapp/src/mocks/commentHandler.mock/teamComments.js
  webapp/src/mocks/commentHandler.mock/userComments.js
  webapp/src/mocks/etcHandler.mock/index.js
  webapp/src/mocks/mockUtils.js
  webapp/src/mocks/teamHandler.mock/editTeamDetail.js
  webapp/src/mocks/teamHandler.mock/index.js
  webapp/src/mocks/teamHandler.mock/team.mock.js
  webapp/src/mocks/teamHandler.mock/teamDetail.js
  webapp/src/mocks/teamHandler.mock/teamsList.js
  webapp/src/mocks/userHandler.mock/essentialInfo.js
  webapp/src/mocks/userHandler.mock/index.js
  webapp/src/mocks/userHandler.mock/user.mock.js
  webapp/src/mocks/userHandler.mock/userDetail.js
  webapp/src/mocks/userHandler.mock/usersList.js
  webapp/src/pages/EssentialInfo/EssentialInfo.stories.jsx
  webapp/src/pages/EssentialInfo/SubPages/EssentialCallback.jsx
  webapp/src/pages/NotAllow/index.jsx
  webapp/src/pages/NotFound/ NoutFound.stories.jsx
  webapp/src/pages/TeamBoard/TeamBoard.stories.jsx
  webapp/src/pages/TeamPost/TeamPost.stories.jsx
  webapp/src/pages/UserBoard/UserBoard.stories.jsx
  webapp/src/pages/UserPost/UserPost.stories.jsx
  webapp/src/utils/index.js
Labels: Update

#265 [FE] 코넥트 설명 유튜브 영상 업로드
  README.md
Labels: Document
